# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero_time_recommend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hero_time_recommend.proto',
  package='herotimerecommend_protos',
  syntax='proto2',
  serialized_pb=_b('\n\x19hero_time_recommend.proto\x12\x18herotimerecommend_protos\"\x98\x01\n\tVideoInfo\x12\x0b\n\x03vid\x18\x01 \x02(\x0c\x12\x12\n\nshare_time\x18\x02 \x02(\r\x12\x15\n\rvideo_praises\x18\x03 \x02(\r\x12\x13\n\x0bvideo_views\x18\x04 \x02(\r\x12\x0c\n\x04type\x18\x05 \x01(\r\x12\x0b\n\x03num\x18\x06 \x01(\r\x12\x0f\n\x07game_id\x18\x07 \x01(\r\x12\x12\n\nvid_source\x18\x08 \x01(\r\"\x9d\x01\n\x14GetRecommendVideoReq\x12\x0f\n\x07game_id\x18\x01 \x02(\r\x12\x0f\n\x07\x61rea_id\x18\x02 \x02(\r\x12\x0c\n\x04type\x18\x03 \x02(\r\x12\x0b\n\x03num\x18\x05 \x02(\r\x12\x10\n\x08\x66rom_num\x18\x06 \x02(\r\x12\x0f\n\x07tag_num\x18\x07 \x01(\r\x12\x0e\n\x06soucre\x18\x08 \x01(\r\x12\x15\n\rreport_source\x18\t \x01(\r\"\xb1\x01\n\x14GetRecommendVideoRsp\x12\x0e\n\x06result\x18\x01 \x02(\r\x12\x0f\n\x07game_id\x18\x02 \x02(\r\x12\x0f\n\x07\x61rea_id\x18\x03 \x02(\r\x12\x37\n\nvideo_list\x18\x04 \x03(\x0b\x32#.herotimerecommend_protos.VideoInfo\x12\x0f\n\x07\x65rr_msg\x18\x05 \x01(\x0c\x12\x0f\n\x07is_over\x18\x06 \x01(\r\x12\x0c\n\x04next\x18\x07 \x01(\r*-\n\x15herotimesvr_cmd_types\x12\x14\n\x0f\x43MD_HEROTIMESVR\x10\xb0\x08*:\n\x18herotimesvr_subcmd_types\x12\x1e\n\x1aSUBCMD_GET_RECOMMEND_VIDEO\x10\x01\x42\x36\n\x1e\x63om.qt.qq.herotimerecommendsvrB\x14herotimerecommendsvr')
)

_HEROTIMESVR_CMD_TYPES = _descriptor.EnumDescriptor(
  name='herotimesvr_cmd_types',
  full_name='herotimerecommend_protos.herotimesvr_cmd_types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_HEROTIMESVR', index=0, number=1072,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=550,
  serialized_end=595,
)
_sym_db.RegisterEnumDescriptor(_HEROTIMESVR_CMD_TYPES)

herotimesvr_cmd_types = enum_type_wrapper.EnumTypeWrapper(_HEROTIMESVR_CMD_TYPES)
_HEROTIMESVR_SUBCMD_TYPES = _descriptor.EnumDescriptor(
  name='herotimesvr_subcmd_types',
  full_name='herotimerecommend_protos.herotimesvr_subcmd_types',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUBCMD_GET_RECOMMEND_VIDEO', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=597,
  serialized_end=655,
)
_sym_db.RegisterEnumDescriptor(_HEROTIMESVR_SUBCMD_TYPES)

herotimesvr_subcmd_types = enum_type_wrapper.EnumTypeWrapper(_HEROTIMESVR_SUBCMD_TYPES)
CMD_HEROTIMESVR = 1072
SUBCMD_GET_RECOMMEND_VIDEO = 1



_VIDEOINFO = _descriptor.Descriptor(
  name='VideoInfo',
  full_name='herotimerecommend_protos.VideoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vid', full_name='herotimerecommend_protos.VideoInfo.vid', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='share_time', full_name='herotimerecommend_protos.VideoInfo.share_time', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_praises', full_name='herotimerecommend_protos.VideoInfo.video_praises', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_views', full_name='herotimerecommend_protos.VideoInfo.video_views', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='herotimerecommend_protos.VideoInfo.type', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='herotimerecommend_protos.VideoInfo.num', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='herotimerecommend_protos.VideoInfo.game_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vid_source', full_name='herotimerecommend_protos.VideoInfo.vid_source', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=208,
)


_GETRECOMMENDVIDEOREQ = _descriptor.Descriptor(
  name='GetRecommendVideoReq',
  full_name='herotimerecommend_protos.GetRecommendVideoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='herotimerecommend_protos.GetRecommendVideoReq.game_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_id', full_name='herotimerecommend_protos.GetRecommendVideoReq.area_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='herotimerecommend_protos.GetRecommendVideoReq.type', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num', full_name='herotimerecommend_protos.GetRecommendVideoReq.num', index=3,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_num', full_name='herotimerecommend_protos.GetRecommendVideoReq.from_num', index=4,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_num', full_name='herotimerecommend_protos.GetRecommendVideoReq.tag_num', index=5,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='soucre', full_name='herotimerecommend_protos.GetRecommendVideoReq.soucre', index=6,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='report_source', full_name='herotimerecommend_protos.GetRecommendVideoReq.report_source', index=7,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=368,
)


_GETRECOMMENDVIDEORSP = _descriptor.Descriptor(
  name='GetRecommendVideoRsp',
  full_name='herotimerecommend_protos.GetRecommendVideoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='herotimerecommend_protos.GetRecommendVideoRsp.result', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='herotimerecommend_protos.GetRecommendVideoRsp.game_id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_id', full_name='herotimerecommend_protos.GetRecommendVideoRsp.area_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='video_list', full_name='herotimerecommend_protos.GetRecommendVideoRsp.video_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='herotimerecommend_protos.GetRecommendVideoRsp.err_msg', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_over', full_name='herotimerecommend_protos.GetRecommendVideoRsp.is_over', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next', full_name='herotimerecommend_protos.GetRecommendVideoRsp.next', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=548,
)

_GETRECOMMENDVIDEORSP.fields_by_name['video_list'].message_type = _VIDEOINFO
DESCRIPTOR.message_types_by_name['VideoInfo'] = _VIDEOINFO
DESCRIPTOR.message_types_by_name['GetRecommendVideoReq'] = _GETRECOMMENDVIDEOREQ
DESCRIPTOR.message_types_by_name['GetRecommendVideoRsp'] = _GETRECOMMENDVIDEORSP
DESCRIPTOR.enum_types_by_name['herotimesvr_cmd_types'] = _HEROTIMESVR_CMD_TYPES
DESCRIPTOR.enum_types_by_name['herotimesvr_subcmd_types'] = _HEROTIMESVR_SUBCMD_TYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoInfo = _reflection.GeneratedProtocolMessageType('VideoInfo', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOINFO,
  __module__ = 'hero_time_recommend_pb2'
  # @@protoc_insertion_point(class_scope:herotimerecommend_protos.VideoInfo)
  ))
_sym_db.RegisterMessage(VideoInfo)

GetRecommendVideoReq = _reflection.GeneratedProtocolMessageType('GetRecommendVideoReq', (_message.Message,), dict(
  DESCRIPTOR = _GETRECOMMENDVIDEOREQ,
  __module__ = 'hero_time_recommend_pb2'
  # @@protoc_insertion_point(class_scope:herotimerecommend_protos.GetRecommendVideoReq)
  ))
_sym_db.RegisterMessage(GetRecommendVideoReq)

GetRecommendVideoRsp = _reflection.GeneratedProtocolMessageType('GetRecommendVideoRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETRECOMMENDVIDEORSP,
  __module__ = 'hero_time_recommend_pb2'
  # @@protoc_insertion_point(class_scope:herotimerecommend_protos.GetRecommendVideoRsp)
  ))
_sym_db.RegisterMessage(GetRecommendVideoRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.qt.qq.herotimerecommendsvrB\024herotimerecommendsvr'))
# @@protoc_insertion_point(module_scope)
